name: Deploy Plugins TopSky

on:
  push:
    paths:
      - "Plugins/TopSky/**"
    branches:
      - main

jobs:
  deploy_tpl_issue_afrc:
    name: "Deploy TopSky Plugins to AFRC"
    runs-on: ubuntu-latest
    steps:
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACT_COPY_TO_REPO_PAT }}
        with:
          source-directory: Plugins/TopSky
          destination-github-username: "VATSIM-SSA"
          destination-repository-name: "sectorfile-afrc"
          user-email: 30835922+miguelalbano@users.noreply.github.com
          target-branch: main
          target-directory: "Plugins/TopSky"
          create-target-branch-if-needed: false
          commit-message: "update: topsky plugin"
  deploy_tpl_issue_afrs:
    name: "Deploy TopSky Plugins to AFRS"
    runs-on: ubuntu-latest
    steps:
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACT_COPY_TO_REPO_PAT }}
        with:
          source-directory: repository-management/templates/issues
          destination-github-username: "VATSIM-SSA"
          destination-repository-name: "sectorfile-afrs"
          user-email: 30835922+miguelalbano@users.noreply.github.com
          target-branch: main
          target-directory: ".github/ISSUE_TEMPLATE"
          create-target-branch-if-needed: false
          commit-message: "update: topsky plugin"
  deploy_tpl_issue_afrw:
    name: "Deploy TopSky Plugins to AFRW"
    runs-on: ubuntu-latest
    steps:
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACT_COPY_TO_REPO_PAT }}
        with:
          source-directory: repository-management/templates/issues
          destination-github-username: "VATSIM-SSA"
          destination-repository-name: "sectorfile-afrw"
          user-email: 30835922+miguelalbano@users.noreply.github.com
          target-branch: main
          target-directory: ".github/ISSUE_TEMPLATE"
          create-target-branch-if-needed: false
          commit-message: "update: topsky plugin"
  deploy_tpl_issue_dgac:
    name: "Deploy TopSky Plugins to DGAC"
    runs-on: ubuntu-latest
    steps:
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACT_COPY_TO_REPO_PAT }}
        with:
          source-directory: repository-management/templates/issues
          destination-github-username: "VATSIM-SSA"
          destination-repository-name: "sectorfile-dgac"
          user-email: 30835922+miguelalbano@users.noreply.github.com
          target-branch: main
          target-directory: ".github/ISSUE_TEMPLATE"
          create-target-branch-if-needed: false
          commit-message: "update: topsky plugin"
  deploy_tpl_issue_dnkk:
    name: "Deploy TopSky Plugins to DNKK"
    runs-on: ubuntu-latest
    steps:
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACT_COPY_TO_REPO_PAT }}
        with:
          source-directory: repository-management/templates/issues
          destination-github-username: "VATSIM-SSA"
          destination-repository-name: "sectorfile-dnkk"
          user-email: 30835922+miguelalbano@users.noreply.github.com
          target-branch: main
          target-directory: ".github/ISSUE_TEMPLATE"
          create-target-branch-if-needed: false
          commit-message: "update: topsky plugin"
  deploy_tpl_issue_fajo:
    name: "Deploy TopSky Plugins to FAJO"
    runs-on: ubuntu-latest
    steps:
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACT_COPY_TO_REPO_PAT }}
        with:
          source-directory: repository-management/templates/issues
          destination-github-username: "VATSIM-SSA"
          destination-repository-name: "sectorfile-fajo"
          user-email: 30835922+miguelalbano@users.noreply.github.com
          target-branch: main
          target-directory: ".github/ISSUE_TEMPLATE"
          create-target-branch-if-needed: false
          commit-message: "update: topsky plugin"
  deploy_tpl_issue_fasa:
    name: "Deploy TopSky Plugins to FASA"
    runs-on: ubuntu-latest
    steps:
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACT_COPY_TO_REPO_PAT }}
        with:
          source-directory: repository-management/templates/issues
          destination-github-username: "VATSIM-SSA"
          destination-repository-name: "sectorfile-fasa"
          user-email: 30835922+miguelalbano@users.noreply.github.com
          target-branch: main
          target-directory: ".github/ISSUE_TEMPLATE"
          create-target-branch-if-needed: false
          commit-message: "update: topsky plugin"
  deploy_tpl_issue_fbgr:
    name: "Deploy TopSky Plugins to FBGR"
    runs-on: ubuntu-latest
    steps:
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACT_COPY_TO_REPO_PAT }}
        with:
          source-directory: repository-management/templates/issues
          destination-github-username: "VATSIM-SSA"
          destination-repository-name: "sectorfile-fbgr"
          user-email: 30835922+miguelalbano@users.noreply.github.com
          target-branch: main
          target-directory: ".github/ISSUE_TEMPLATE"
          create-target-branch-if-needed: false
          commit-message: "update: topsky plugin"
  deploy_tpl_issue_fccc:
    name: "Deploy TopSky Plugins to FCCC"
    runs-on: ubuntu-latest
    steps:
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACT_COPY_TO_REPO_PAT }}
        with:
          source-directory: repository-management/templates/issues
          destination-github-username: "VATSIM-SSA"
          destination-repository-name: "sectorfile-fccc"
          user-email: 30835922+miguelalbano@users.noreply.github.com
          target-branch: main
          target-directory: ".github/ISSUE_TEMPLATE"
          create-target-branch-if-needed: false
          commit-message: "update: topsky plugin"
  deploy_tpl_issue_fimm:
    name: "Deploy TopSky Plugins to FIMM"
    runs-on: ubuntu-latest
    steps:
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACT_COPY_TO_REPO_PAT }}
        with:
          source-directory: repository-management/templates/issues
          destination-github-username: "VATSIM-SSA"
          destination-repository-name: "sectorfile-fimm"
          user-email: 30835922+miguelalbano@users.noreply.github.com
          target-branch: main
          target-directory: ".github/ISSUE_TEMPLATE"
          create-target-branch-if-needed: false
          commit-message: "update: topsky plugin"
  deploy_tpl_issue_flfi:
    name: "Deploy TopSky Plugins to FLFI"
    runs-on: ubuntu-latest
    steps:
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACT_COPY_TO_REPO_PAT }}
        with:
          source-directory: repository-management/templates/issues
          destination-github-username: "VATSIM-SSA"
          destination-repository-name: "sectorfile-flfi"
          user-email: 30835922+miguelalbano@users.noreply.github.com
          target-branch: main
          target-directory: ".github/ISSUE_TEMPLATE"
          create-target-branch-if-needed: false
          commit-message: "update: topsky plugin"
  deploy_tpl_issue_fmmm:
    name: "Deploy TopSky Plugins to FMMM"
    runs-on: ubuntu-latest
    steps:
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACT_COPY_TO_REPO_PAT }}
        with:
          source-directory: repository-management/templates/issues
          destination-github-username: "VATSIM-SSA"
          destination-repository-name: "sectorfile-fmmm"
          user-email: 30835922+miguelalbano@users.noreply.github.com
          target-branch: main
          target-directory: ".github/ISSUE_TEMPLATE"
          create-target-branch-if-needed: false
          commit-message: "update: topsky plugin"
  deploy_tpl_issue_fnan:
    name: "Deploy TopSky Plugins to FNAN"
    runs-on: ubuntu-latest
    steps:
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACT_COPY_TO_REPO_PAT }}
        with:
          source-directory: repository-management/templates/issues
          destination-github-username: "VATSIM-SSA"
          destination-repository-name: "sectorfile-fnan"
          user-email: 30835922+miguelalbano@users.noreply.github.com
          target-branch: main
          target-directory: ".github/ISSUE_TEMPLATE"
          create-target-branch-if-needed: false
          commit-message: "update: topsky plugin"
  deploy_tpl_issue_fqbe:
    name: "Deploy TopSky Plugins to FQBE"
    runs-on: ubuntu-latest
    steps:
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACT_COPY_TO_REPO_PAT }}
        with:
          source-directory: repository-management/templates/issues
          destination-github-username: "VATSIM-SSA"
          destination-repository-name: "sectorfile-fqbe"
          user-email: 30835922+miguelalbano@users.noreply.github.com
          target-branch: main
          target-directory: ".github/ISSUE_TEMPLATE"
          create-target-branch-if-needed: false
          commit-message: "update: topsky plugin"
  deploy_tpl_issue_fsss:
    name: "Deploy TopSky Plugins to FSSS"
    runs-on: ubuntu-latest
    steps:
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACT_COPY_TO_REPO_PAT }}
        with:
          source-directory: repository-management/templates/issues
          destination-github-username: "VATSIM-SSA"
          destination-repository-name: "sectorfile-fsss"
          user-email: 30835922+miguelalbano@users.noreply.github.com
          target-branch: main
          target-directory: ".github/ISSUE_TEMPLATE"
          create-target-branch-if-needed: false
          commit-message: "update: topsky plugin"
  deploy_tpl_issue_fvhf:
    name: "Deploy TopSky Plugins to FVHF"
    runs-on: ubuntu-latest
    steps:
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACT_COPY_TO_REPO_PAT }}
        with:
          source-directory: repository-management/templates/issues
          destination-github-username: "VATSIM-SSA"
          destination-repository-name: "sectorfile-fvhf"
          user-email: 30835922+miguelalbano@users.noreply.github.com
          target-branch: main
          target-directory: ".github/ISSUE_TEMPLATE"
          create-target-branch-if-needed: false
          commit-message: "update: topsky plugin"
  deploy_tpl_issue_fwll:
    name: "Deploy TopSky Plugins to FWLL"
    runs-on: ubuntu-latest
    steps:
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACT_COPY_TO_REPO_PAT }}
        with:
          source-directory: repository-management/templates/issues
          destination-github-username: "VATSIM-SSA"
          destination-repository-name: "sectorfile-fwll"
          user-email: 30835922+miguelalbano@users.noreply.github.com
          target-branch: main
          target-directory: ".github/ISSUE_TEMPLATE"
          create-target-branch-if-needed: false
          commit-message: "update: topsky plugin"
  deploy_tpl_issue_fywf:
    name: "Deploy TopSky Plugins to FYWF"
    runs-on: ubuntu-latest
    steps:
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACT_COPY_TO_REPO_PAT }}
        with:
          source-directory: repository-management/templates/issues
          destination-github-username: "VATSIM-SSA"
          destination-repository-name: "sectorfile-fywf"
          user-email: 30835922+miguelalbano@users.noreply.github.com
          target-branch: main
          target-directory: ".github/ISSUE_TEMPLATE"
          create-target-branch-if-needed: false
          commit-message: "update: topsky plugin"
  deploy_tpl_issue_fzza:
    name: "Deploy TopSky Plugins to FZZA"
    runs-on: ubuntu-latest
    steps:
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACT_COPY_TO_REPO_PAT }}
        with:
          source-directory: repository-management/templates/issues
          destination-github-username: "VATSIM-SSA"
          destination-repository-name: "sectorfile-fzza"
          user-email: 30835922+miguelalbano@users.noreply.github.com
          target-branch: main
          target-directory: ".github/ISSUE_TEMPLATE"
          create-target-branch-if-needed: false
          commit-message: "update: topsky plugin"
  deploy_tpl_issue_gooo:
    name: "Deploy TopSky Plugins to GOOO"
    runs-on: ubuntu-latest
    steps:
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACT_COPY_TO_REPO_PAT }}
        with:
          source-directory: repository-management/templates/issues
          destination-github-username: "VATSIM-SSA"
          destination-repository-name: "sectorfile-gooo"
          user-email: 30835922+miguelalbano@users.noreply.github.com
          target-branch: main
          target-directory: ".github/ISSUE_TEMPLATE"
          create-target-branch-if-needed: false
          commit-message: "update: topsky plugin"
  deploy_tpl_issue_goooo:
    name: "Deploy TopSky Plugins to GOOOO"
    runs-on: ubuntu-latest
    steps:
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACT_COPY_TO_REPO_PAT }}
        with:
          source-directory: repository-management/templates/issues
          destination-github-username: "VATSIM-SSA"
          destination-repository-name: "sectorfile-goooo"
          user-email: 30835922+miguelalbano@users.noreply.github.com
          target-branch: main
          target-directory: ".github/ISSUE_TEMPLATE"
          create-target-branch-if-needed: false
          commit-message: "update: topsky plugin"
  deploy_tpl_issue_gvsc:
    name: "Deploy TopSky Plugins to GVSC"
    runs-on: ubuntu-latest
    steps:
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACT_COPY_TO_REPO_PAT }}
        with:
          source-directory: repository-management/templates/issues
          destination-github-username: "VATSIM-SSA"
          destination-repository-name: "sectorfile-gvsc"
          user-email: 30835922+miguelalbano@users.noreply.github.com
          target-branch: main
          target-directory: ".github/ISSUE_TEMPLATE"
          create-target-branch-if-needed: false
          commit-message: "update: topsky plugin"
  deploy_tpl_issue_hkna:
    name: "Deploy TopSky Plugins to HKNA"
    runs-on: ubuntu-latest
    steps:
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACT_COPY_TO_REPO_PAT }}
        with:
          source-directory: repository-management/templates/issues
          destination-github-username: "VATSIM-SSA"
          destination-repository-name: "sectorfile-hkna"
          user-email: 30835922+miguelalbano@users.noreply.github.com
          target-branch: main
          target-directory: ".github/ISSUE_TEMPLATE"
          create-target-branch-if-needed: false
          commit-message: "update: topsky plugin"
  deploy_tpl_issue_htdc:
    name: "Deploy TopSky Plugins to HTDC"
    runs-on: ubuntu-latest
    steps:
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACT_COPY_TO_REPO_PAT }}
        with:
          source-directory: repository-management/templates/issues
          destination-github-username: "VATSIM-SSA"
          destination-repository-name: "sectorfile-htdc"
          user-email: 30835922+miguelalbano@users.noreply.github.com
          target-branch: main
          target-directory: ".github/ISSUE_TEMPLATE"
          create-target-branch-if-needed: false
          commit-message: "update: topsky plugin"
  deploy_tpl_issue_huec:
    name: "Deploy TopSky Plugins to HUEC"
    runs-on: ubuntu-latest
    steps:
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACT_COPY_TO_REPO_PAT }}
        with:
          source-directory: repository-management/templates/issues
          destination-github-username: "VATSIM-SSA"
          destination-repository-name: "sectorfile-huec"
          user-email: 30835922+miguelalbano@users.noreply.github.com
          target-branch: main
          target-directory: ".github/ISSUE_TEMPLATE"
          create-target-branch-if-needed: false
          commit-message: "update: topsky plugin"
